enum IdleScreenPixelMaterialsInspectorContract {
    static let controlLabels = [
        "Material",
        "Terrain",
        "Palette",
        "Seed",
        "Basin count",
        "Basin depth",
        "Minimum basin capacity",
        "Channel connectivity",
        "Channel width",
        "Rock ratio",
        "Soil ratio",
        "Emitter count",
        "Emitter position",
        "Emitter width",
        "Emitter rate",
        "Cell scale",
        "Gravity",
        "Lateral flow",
        "Equalization",
        "Water pressure",
        "Spill rate",
        "Drain rate",
        "Evaporation rate",
        "Obstacle density",
        "Persistence",
        "Quiet duration",
        "Fill duration",
        "Settled duration",
        "Drain duration",
        "Regeneration",
    ]
}
