#!/bin/bash

set -euo pipefail

usage() {
  echo "Usage: $0 /absolute/path/to/IdleScreenR1ReleaseCandidateV1.txt /absolute/path/to/new-idlescreen.rb" >&2
  exit 64
}

[[ $# -eq 2 ]] || usage

script_root="$(cd "$(dirname "$0")" && pwd)"
common="$script_root/r1-release-candidate-common.sh"
[[ -f "$common" ]] || {
  echo "FAIL: release candidate support is incomplete." >&2
  exit 66
}
# shellcheck disable=SC1090
source "$common"

fixture_mode="${IDLESCREEN_HOMEBREW_FIXTURE_MODE:-NO}"
candidate_verifier_override="${IDLESCREEN_HOMEBREW_CANDIDATE_VERIFIER:-}"
[[ "$fixture_mode" == YES || "$fixture_mode" == NO ]] || usage
if [[ "$fixture_mode" == YES ]]; then
  [[ -n "$candidate_verifier_override" && -x "$candidate_verifier_override" ]] || {
    echo "FAIL: fixture mode requires an explicit candidate verifier." >&2
    exit 64
  }
  candidate_verifier="$candidate_verifier_override"
else
  [[ -z "$candidate_verifier_override" ]] || {
    echo "FAIL: candidate verifier overrides require explicit fixture mode." >&2
    exit 64
  }
  candidate_verifier="$script_root/verify-r1-release-candidate.sh"
  [[ -x "$candidate_verifier" ]] || {
    echo "FAIL: release candidate verifier is missing." >&2
    exit 66
  }
fi

manifest="$1"
requested_output="$2"
[[ "$manifest" = /* && "$requested_output" = /* ]] || usage
[[ -f "$manifest" && ! -L "$manifest" ]] || {
  echo "FAIL: release candidate manifest is missing or is a symbolic link." >&2
  exit 66
}

output_parent="$(/usr/bin/dirname "$requested_output")"
output_leaf="$(/usr/bin/basename "$requested_output")"
[[ -n "$output_leaf" && "$output_leaf" != . && "$output_leaf" != .. ]] || usage
[[ -d "$output_parent" && ! -L "$output_parent" ]] || {
  echo "FAIL: cask output parent must be an existing non-symlink directory." >&2
  exit 66
}
output_parent="$(/bin/realpath "$output_parent")"
output="$output_parent/$output_leaf"
[[ ! -e "$output" && ! -L "$output" ]] || {
  echo "FAIL: refusing to replace existing cask output: $output" >&2
  exit 73
}

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

manifest_value() {
  r1_manifest_value "$manifest" "$1" || fail "candidate manifest has no unique $1"
}

[[ "$(manifest_value schema)" == IdleScreenR1ReleaseCandidate/v1 ]] ||
  fail "unexpected release candidate schema"
[[ "$(manifest_value verification_mode)" == release ]] ||
  fail "Homebrew publication requires a real release candidate"
[[ "$(manifest_value source_clean)" == true ]] ||
  fail "Homebrew publication requires a clean source build"
[[ "$(manifest_value notary_status)" == Accepted ]] ||
  fail "candidate notarization was not accepted"
[[ "$(manifest_value notary_issue_count)" == 0 ]] ||
  fail "candidate notarization log contains issues"
[[ "$(manifest_value stapler_status)" == valid ]] ||
  fail "candidate does not contain a valid stapled ticket"
[[ "$(manifest_value dmg_gatekeeper_status)" == accepted ]] ||
  fail "candidate DMG did not pass Gatekeeper"
[[ "$(manifest_value mounted_app_gatekeeper_status)" == accepted ]] ||
  fail "candidate app did not pass Gatekeeper"

bundle_short_version="$(manifest_value bundle_short_version)"
bundle_version="$(manifest_value bundle_version)"
[[ "$bundle_short_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ||
  fail "candidate version must be a stable semantic version"
[[ "$bundle_version" =~ ^[1-9][0-9]*$ ]] || fail "candidate build version is malformed"

dmg_relative_path="$(manifest_value dmg_relative_path)"
[[ "$dmg_relative_path" == "Distribution/idlescreen-$bundle_short_version-build$bundle_version.dmg" ]] ||
  fail "candidate DMG path is not canonical"
manifest_root="$(/bin/realpath "$(/usr/bin/dirname "$manifest")")" ||
  fail "could not resolve release candidate directory"
dmg="$manifest_root/$dmg_relative_path"
[[ -f "$dmg" && ! -L "$dmg" ]] || fail "candidate DMG is missing or is a symbolic link"
[[ "$(/bin/realpath "$dmg")" == "$dmg" ]] || fail "candidate DMG path escapes its release directory"

expected_sha256="$(manifest_value stapled_dmg_sha256)"
[[ "$expected_sha256" =~ ^[0-9a-f]{64}$ ]] || fail "candidate DMG checksum is malformed"
[[ "$(r1_sha256_file "$dmg")" == "$expected_sha256" ]] ||
  fail "candidate DMG differs from its stapled checksum"
"$candidate_verifier" "$dmg" "$manifest" >/dev/null ||
  fail "release candidate verification replay failed"

temporary_output="$(mktemp "$output_parent/.$output_leaf.tmp.XXXXXX")" ||
  fail "could not create a private cask output"
trap '/bin/rm -f "${temporary_output:?}"' EXIT
{
  echo '# This file was generated by idlescreen. DO NOT EDIT.'
  echo 'cask "idlescreen" do'
  /usr/bin/printf '  version "%s,%s"\n' "$bundle_short_version" "$bundle_version"
  /usr/bin/printf '  sha256 "%s"\n' "$expected_sha256"
  echo
  echo '  url "https://github.com/CodesWhat/idlescreen/releases/download/v#{version.csv.first}/idlescreen-#{version.csv.first}-build#{version.csv.second}.dmg"'
  echo '  name "idlescreen"'
  echo '  desc "Metal-rendered ASCII art screen saver"'
  echo '  homepage "https://github.com/CodesWhat/idlescreen"'
  echo
  echo '  livecheck do'
  echo '    skip "Auto-generated on release."'
  echo '  end'
  echo
  echo '  depends_on macos: :tahoe'
  echo
  echo '  app "IdleScreen.app", target: "idlescreen.app"'
  echo
  echo '  uninstall quit: "com.idlescreen.app"'
  echo
  echo '  zap trash: ['
  echo '    "~/Library/Application Support/Idlescreen",'
  echo '    "~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Idlescreen",'
  echo '    "~/Library/Group Containers/group.com.idlescreen.shared",'
  echo '    "~/Library/Preferences/com.idlescreen.app.plist",'
  echo '    "~/Library/Saved Application State/com.idlescreen.app.savedState",'
  echo '  ]'
  echo
  echo '  caveats <<~EOS'
  echo '    Open idlescreen once after installation, then enable it in System Settings > Wallpaper > Screen Saver.'
  echo '    Camera access is requested only if you enable a camera-based effect.'
  echo '  EOS'
  echo 'end'
} >"$temporary_output"

/bin/chmod 0644 "$temporary_output"
if ! /bin/ln "$temporary_output" "$output"; then
  fail "refusing to replace cask output created during generation: $output"
fi
/bin/rm "$temporary_output"
trap - EXIT

echo "Generated Homebrew cask: $output"
