#!/bin/bash

set -euo pipefail

project_root="$(cd "$(dirname "$0")/.." && pwd)"
project_file="$project_root/project.yml"

screen_saver_block="$({
  awk '
    /^targets:$/ { in_targets = 1; next }
    in_targets && /^  IdleScreenScreenSaver:$/ { in_target = 1 }
    in_target && /^  [[:alnum:]_]+:$/ && $0 != "  IdleScreenScreenSaver:" { exit }
    in_target { print }
  ' "$project_file"
})"
app_block="$({
  awk '
    /^targets:$/ { in_targets = 1; next }
    in_targets && /^  IdleScreenApp:$/ { in_target = 1 }
    in_target && /^  [[:alnum:]_]+:$/ && $0 != "  IdleScreenApp:" { exit }
    in_target { print }
  ' "$project_file"
})"
c3_archive_block="$({
  awk '
    /^targets:$/ { in_targets = 1; next }
    in_targets && /^  IdleScreenC3ArchiveBundle:$/ { in_target = 1 }
    in_target && /^  [[:alnum:]_]+:$/ && $0 != "  IdleScreenC3ArchiveBundle:" { exit }
    in_target { print }
  ' "$project_file"
})"

if ! grep -Fq 'CURRENT_PROJECT_VERSION: "64"' <<<"$screen_saver_block" ||
   ! grep -Fq 'MARKETING_VERSION: "0.1.2"' <<<"$screen_saver_block" ||
   ! grep -Fq 'CFBundleShortVersionString: "0.1.2"' <<<"$app_block" ||
   ! grep -Fq 'CFBundleVersion: "64"' <<<"$app_block" ||
   ! grep -Fq 'CFBundleShortVersionString: "0.1.2"' <<<"$c3_archive_block" ||
   ! grep -Fq 'CFBundleVersion: "64"' <<<"$c3_archive_block"; then
  echo "FAIL: v0.1.2 must ship build 64 consistently across every production bundle." >&2
  exit 1
fi

echo "PASS: v0.1.2 uses build 64 consistently across every production bundle."

generator="$project_root/scripts/generate-homebrew-cask.sh"
sbom_generator="$project_root/scripts/generate-release-sbom.sh"
[[ -x "$generator" ]] || {
  echo "FAIL: the release must provide an executable Homebrew cask generator." >&2
  exit 1
}
[[ -x "$sbom_generator" ]] || {
  echo "FAIL: the release must provide an executable SPDX SBOM generator." >&2
  exit 1
}
ci_workflow="$project_root/.github/workflows/ci-verify.yml"
if [[ "$(grep -Fc './scripts/test-public-release-contract.sh' "$ci_workflow" || true)" -ne 1 ]]; then
  echo "FAIL: CI must run the public release contract exactly once." >&2
  exit 1
fi

scratch_root="$(mktemp -d /tmp/idlescreen-homebrew-contract.XXXXXX)"
trap '/bin/rm -rf "${scratch_root:?}"' EXIT
candidate_root="$scratch_root/candidate"
distribution_root="$candidate_root/Distribution"
manifest="$candidate_root/IdleScreenR1ReleaseCandidateV1.txt"
cask="$scratch_root/idlescreen.rb"
sbom="$scratch_root/idlescreen-0.1.2-build64.spdx.json"
verifier="$scratch_root/verify-candidate.sh"
verifier_marker="$scratch_root/verifier-arguments.txt"
/bin/mkdir -p "$distribution_root"
/usr/bin/printf 'notarized fixture dmg\n' >"$distribution_root/idlescreen-0.1.2-build64.dmg"
dmg_sha256="$(/usr/bin/shasum -a 256 "$distribution_root/idlescreen-0.1.2-build64.dmg" | /usr/bin/awk '{ print $1 }')"
source_commit="$(git -C "$project_root" rev-parse HEAD)"

{
  echo '#!/bin/bash'
  echo 'set -euo pipefail'
  echo '[[ $# -eq 2 ]]'
  echo '/usr/bin/printf "%s\n%s\n" "$1" "$2" >"${IDLESCREEN_HOMEBREW_VERIFIER_MARKER:?}"'
  echo 'if [[ -n "${IDLESCREEN_HOMEBREW_RACE_OUTPUT:-}" ]]; then'
  echo '  /usr/bin/printf "attacker-owned\n" >"$IDLESCREEN_HOMEBREW_RACE_OUTPUT"'
  echo 'fi'
} >"$verifier"
/bin/chmod +x "$verifier"

generate_fixture_cask() {
  IDLESCREEN_HOMEBREW_FIXTURE_MODE=YES \
  IDLESCREEN_HOMEBREW_CANDIDATE_VERIFIER="$verifier" \
  IDLESCREEN_HOMEBREW_VERIFIER_MARKER="$verifier_marker" \
    "$generator" "$@"
}

generate_fixture_sbom() {
  IDLESCREEN_SBOM_FIXTURE_MODE=YES \
  IDLESCREEN_SBOM_CANDIDATE_VERIFIER="$verifier" \
  IDLESCREEN_HOMEBREW_VERIFIER_MARKER="$verifier_marker" \
    "$sbom_generator" "$@"
}

{
  echo 'schema=IdleScreenR1ReleaseCandidate/v1'
  echo 'verification_mode=release'
  echo 'source_clean=true'
  /usr/bin/printf 'source_commit=%s\n' "$source_commit"
  echo 'bundle_short_version=0.1.2'
  echo 'bundle_version=64'
  echo 'dmg_relative_path=Distribution/idlescreen-0.1.2-build64.dmg'
  echo 'notary_status=Accepted'
  echo 'notary_issue_count=0'
  echo 'stapler_status=valid'
  echo 'dmg_gatekeeper_status=accepted'
  echo 'mounted_app_gatekeeper_status=accepted'
  /usr/bin/printf 'stapled_dmg_sha256=%s\n' "$dmg_sha256"
} >"$manifest"

generate_fixture_cask "$manifest" "$cask"
/usr/bin/ruby -c "$cask" >/dev/null
[[ "$(/usr/bin/sed -n '2p' "$verifier_marker" 2>/dev/null || true)" == "$manifest" ]] || {
  echo "FAIL: the cask generator did not replay the release candidate verifier." >&2
  exit 1
}

for required_text in \
  '# This file was generated by idlescreen. DO NOT EDIT.' \
  'cask "idlescreen" do' \
  'version "0.1.2,64"' \
  "sha256 \"$dmg_sha256\"" \
  'releases/download/v#{version.csv.first}/idlescreen-#{version.csv.first}-build#{version.csv.second}.dmg' \
  'desc "Metal-rendered ASCII art screen saver"' \
  'skip "Auto-generated on release."' \
  'depends_on macos: :tahoe' \
  'app "IdleScreen.app", target: "idlescreen.app"' \
  'quit: "com.idlescreen.app"' \
  'group.com.idlescreen.shared'; do
  if ! grep -Fq "$required_text" "$cask"; then
    echo "FAIL: generated cask is missing: $required_text" >&2
    exit 1
  fi
done

cask_has_separated_url() {
  /usr/bin/awk '
    /^  sha256 / { saw_sha = 1; next }
    saw_sha && /^$/ { saw_gap = 1; next }
    saw_sha && /^  url / { saw_url = 1; exit saw_gap ? 0 : 1 }
    saw_sha { exit 1 }
    END { if (!saw_sha || !saw_url) exit 1 }
  ' "$1"
}

if ! cask_has_separated_url "$cask"; then
  echo "FAIL: generated cask does not separate the URL stanza group." >&2
  exit 1
fi

generate_fixture_sbom "$manifest" "$sbom"
/usr/bin/python3 -c '
import json
import sys

document = json.load(open(sys.argv[1], encoding="utf-8"))
package = next(item for item in document["packages"] if item["name"] == "idlescreen")
assert document["spdxVersion"] == "SPDX-2.3"
assert document["dataLicense"] == "CC0-1.0"
assert document["creationInfo"]["created"].endswith("Z")
assert package["versionInfo"] == "0.1.2"
assert package["checksums"] == [{"algorithm": "SHA256", "checksumValue": sys.argv[2]}]
assert sys.argv[3] in package["sourceInfo"]
' "$sbom" "$dmg_sha256" "$source_commit"

if generate_fixture_sbom "$manifest" "$sbom" >/dev/null 2>&1; then
  echo "FAIL: the SBOM generator overwrote an existing output." >&2
  exit 1
fi

sbom_race_output="$scratch_root/raced.spdx.json"
if IDLESCREEN_HOMEBREW_RACE_OUTPUT="$sbom_race_output" \
  generate_fixture_sbom "$manifest" "$sbom_race_output" >/dev/null 2>&1; then
  echo "FAIL: the SBOM generator overwrote an output created during verification." >&2
  exit 1
fi
if [[ "$(<"$sbom_race_output")" != attacker-owned ]]; then
  echo "FAIL: a raced SBOM output was modified." >&2
  exit 1
fi

missing_url_cask="$scratch_root/missing-url.rb"
/usr/bin/awk '/^  url / { exit } { print }' "$cask" >"$missing_url_cask"
if cask_has_separated_url "$missing_url_cask"; then
  echo "FAIL: the URL stanza separator check accepted a cask without a URL." >&2
  exit 1
fi

race_output="$scratch_root/race-output.rb"
if IDLESCREEN_HOMEBREW_RACE_OUTPUT="$race_output" \
  generate_fixture_cask "$manifest" "$race_output" >/dev/null 2>&1; then
  echo "FAIL: the cask generator overwrote an output created during verification." >&2
  exit 1
fi
if [[ "$(<"$race_output")" != attacker-owned ]]; then
  echo "FAIL: a raced cask output was modified." >&2
  exit 1
fi

bad_manifest="$scratch_root/bad-manifest.txt"
/usr/bin/sed 's/notary_status=Accepted/notary_status=Rejected/' "$manifest" >"$bad_manifest"
if generate_fixture_cask "$bad_manifest" "$scratch_root/rejected.rb" >/dev/null 2>&1; then
  echo "FAIL: the cask generator accepted a rejected notarization." >&2
  exit 1
fi
if generate_fixture_sbom "$bad_manifest" "$scratch_root/rejected.spdx.json" >/dev/null 2>&1; then
  echo "FAIL: the SBOM generator accepted a rejected notarization." >&2
  exit 1
fi

/usr/bin/printf 'tampered\n' >>"$distribution_root/idlescreen-0.1.2-build64.dmg"
if generate_fixture_cask "$manifest" "$scratch_root/tampered.rb" >/dev/null 2>&1; then
  echo "FAIL: the cask generator accepted a DMG checksum mismatch." >&2
  exit 1
fi
if generate_fixture_sbom "$manifest" "$scratch_root/tampered.spdx.json" >/dev/null 2>&1; then
  echo "FAIL: the SBOM generator accepted a DMG checksum mismatch." >&2
  exit 1
fi

echo "PASS: the Homebrew cask and SPDX SBOM are derived only from an accepted, stapled, Gatekeeper-approved build 64 candidate."
