name: "Release: Main is released"

on:
  push:
    branches: [main]
  schedule:
    - cron: "43 9 * * 2"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify:
    uses: CodesWhat/.github/.github/workflows/main-is-released.yml@11004e42d7d19e86eb3b7777c467ec9522b784e1 # main, 2026-08-21
